### ISSUE TITLE
Chrome on IOS

### ISSUE THREAD

**Issue by schulzefelix** [gabrielbull/php-browser#14]
Hi, just a quick notice.

at the moment Chrome for iOS is recognized as Safari. Chrome uses CriOS/xxx in the User Agent.

Referenz:
https://developer.chrome.com/multidevice/user-agent#chrome_for_ios_user_agent

**Comment by gabrielbull** [comment]
Do you have the time to do a PR?

```
Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3
```

**Comment by schulzefelix** [comment]
#15

**Comment by gabrielbull** [comment]
Merged, thanks for the PR!
