### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by ximex** [gabrielbull/php-browser#21]
Detect Windows 10

**Comment by gabrielbull** [comment]
It works now for the Edge user agent string. Do you have other cases where it does not work?

**Comment by ximex** [comment]
i didn't tested anything or used this lib. but i saw that there is no detection for win10 and edge.
I only searched for libs to fix this: https://github.com/Admidio/admidio/issues/58

**Comment by ve3** [comment]
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

Can't detect Windows 10

**Comment by gabrielbull** [comment]
@ve3 You're right, I pushed a fix to that.
