### ISSUE TITLE
Drop PHP 5.3 Support?

### ISSUE THREAD

**Issue by vinkla** [gabrielbull/php-browser#30]
What about dropping PHP 5.3 support? Even 5.4 will stop getting security updates this september (2015). I would even argue for just having 5.5.9 (Symfony 3 and Laravel 5.1 uses this version).

**Comment by gabrielbull** [comment]
I'd rather we keep it for now, there is quite a few people using the library and supporting 5.3 does not add too much effort.

**Comment by vinkla** [comment]
Okay, that's fine. Though, remember to add short_array_syntax to styleci.

**Comment by vinkla** [comment]
Okay, that's fine. Though, remember to add `short_array_syntax` to the `disabled` array config at StyleCI. Otherwise it will continue to fail since it is expecting short array syntax.
